#include "IntVector.h"
#include "ComplexVector.h"
#include "DoubleVector.h"
#include <stdio.h>

void test_int() {
    printf("Int tests:\n");
    printf("Input 6 numbers");
    Vector *v1 = Make_Int_Vector();
    Vector *v2 = Make_Int_Vector();
    int *x1 = calloc(1, sizeof(int));
    int *y1 = calloc(1, sizeof(int));
    int *z1 = calloc(1, sizeof(int));
    int *x2 = calloc(1, sizeof(int));
    int *y2 = calloc(1, sizeof(int));
    int *z2 = calloc(1, sizeof(int));
    for (int i = 0; i < 3; i++) {
        printf("Test number %d\n", i);
        int a = rand() % 100;
        *x1 = a;
        int b = rand() % 100;
        *y1 = b;
        int c = rand() % 100;
        *z1 = c;
        int d = rand() % 100;
        *x2 = d;
        int e = rand() % 100;
        *y2 = e;
        int f = rand() % 100;
        *z2 = f;
        Set_x(v1, (void *) (x1));
        Set_y(v1, (void *) (y1));
        Set_z(v1, (void *) (z1));
        Set_x(v2, (void *) (x2));
        Set_y(v2, (void *) (y2));
        Set_z(v2, (void *) (z2));
        printf("Check Sum_vector:\n");
        printf("Adding vectors:\n");
        print_vector(v1);
        printf(" + ");
        print_vector(v2);
        printf("\n");
        int newx = a + d;
        int newy = b + e;
        int newz = c + f;
        printf("Expected result: (x = %d ,y = %d,z = %d)\nReal result:", newx, newy, newz);
        Vector *res = Sum(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Check subtract_vector:\n");
        printf("Subtracting vectors:\n");
        print_vector(v1);
        printf(" - ");
        print_vector(v2);
        newx = d - a;
        newy = e - b;
        newz = f - c;
        printf("Expected result: (x = %d,y = %d,z = %d)\nReal result:", newx, newy, newz);
        res = Subtract(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Check multiply_vectors:\n");
        printf("Multiplying vectors:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        int mult = a * d + b * e + c * f;
        printf("Expected result: %d\nReal result:", mult);
        void *scalres = Multiply_vectors(v1, v2);
        print_int(scalres);
        printf("\n");
        printf("Check vector_product:\n");
        printf("Multiply vectors:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        int h = b * f - c * e;
        int j = a * f - c * d;
        int k = a * e - b * d;
        printf("Expected result: %di+%dj-%dk\nReal result:", h, j, k);
        Vector_Product(v1, v2);
        printf("\n");
//    int *x1 = (int *) 5, *y1 = (int *) 6, *z1 = (int *) 9;
//    int *x2 = (int *) -10, *y2 = (int *) -3, *z2 = (int *) -7;
//    int *y3 = (int *) 10, *z3 = (int *) 6, *x3 = (int *) 4;
//    Vector *v1 = Make_Int_Vector();
//    Vector *v2 = Make_Int_Vector();
//    Vector *v3 = Make_Int_Vector();
//    Set_x(v1,(void *) (x1));
//    Set_x(v2,(void *) (x2));
//    Set_x(v3,(void *) (x3));
//    Set_y(v1, (void *)(y1));
//    Set_y(v2, (void *)(y2));
//    Set_y(v3, (void *)(y3));
//    Set_z(v1, (void *)(z1));
//    Set_z(v2, (void *)(z2));
//    Set_z(v3, (void *)(z3));
//    printf("Функция Sum_Vector:\n");
//    print_vector(v1);
//    printf(" + ");
//    print_vector(v2);
//    printf("\n");
//    printf("Expected result: (x = %d, y = %d, z = %d)", -5, 3, 2);
//    printf("Real  result:\n");
//    Vector *res = Sum(v1, v2);
//    print_vector(res);
//    printf("\n");

    }
}

void test_double() {
    printf("Double tests:\n");
    printf("Input 6 numbers: ");
    Vector *v1 = Make_Double_Vector();
    Vector *v2 = Make_Double_Vector();
    double *x1 = calloc(1, sizeof(double));
    double *y1 = calloc(1, sizeof(double));
    double *z1 = calloc(1, sizeof(double));
    double *x2 = calloc(1, sizeof(double));
    double *y2 = calloc(1, sizeof(double));
    double *z2 = calloc(1, sizeof(double));
    for (int i = 0; i < 3; i++) {
        printf("Test number %d\n", i);
        double a = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *x1 = a;
        double b = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *y1 = b;
        double c = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *z1 = c;
        double d = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *x2 = d;
        double e = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *y2 = e;
        double f = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *z2 = f;
        Set_x(v1, (void *) (x1));
        Set_y(v1, (void *) (y1));
        Set_z(v1, (void *) (z1));
        Set_x(v2, (void *) (x2));
        Set_y(v2, (void *) (y2));
        Set_z(v2, (void *) (z2));
        printf("Check Sum_vector:\n");
        printf("Adding vectors:\n");
        print_vector(v1);
        printf(" + ");
        print_vector(v2);
        printf("\n");
        double newx = a + d;
        double newy = b + e;
        double newz = c + f;
        printf("Expected result: (x = %lf ,y = %lf ,z = %lf)\nReal result:", newx, newy, newz);
        Vector *res = Sum(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Проверка функции subtract_vector:\n");
        printf("Вычитаем вектора:\n");
        print_vector(v1);
        printf(" - ");
        print_vector(v2);
        newx = d - a;
        newy = e - b;
        newz = f - c;
        printf("Expected result: (x = %lf,y = %lf,z = %lf)\nReal result:", newx, newy, newz);
        res = Subtract(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Check multiply vectors:\n");
        printf("Scalar product:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        double mult = a * d + b * e + c * f;
        printf("Expected result: %lf\nReal result:", mult);
        void *scalres = Multiply_vectors(v1, v2);
        print_double(scalres);
        printf("\n");
        printf("Check vector_product:\n");
        printf("Vector product is:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        double h = b * f - c * e;
        double j = a * f - c * d;
        double k = a * e - b * d;
        printf("Expected result: %lfi+%lfj-%lfk\nReal result:", h, j, k);
        Vector_Product(v1, v2);
        printf("\n");

    }
}

void test_complex() {
    printf("Complex tests:\n");
    printf("Input 12 numbers");
    Vector *v1 = Make_Complex_Vector();
    Vector *v2 = Make_Complex_Vector();
    Complex *x1 = calloc(1, sizeof(Complex));
    Complex *y1 = calloc(1, sizeof(Complex));
    Complex *z1 = calloc(1, sizeof(Complex));
    Complex *x2 = calloc(1, sizeof(Complex));
    Complex *y2 = calloc(1, sizeof(Complex));
    Complex *z2 = calloc(1, sizeof(Complex));
    for (int i = 0; i < 3; i++) {
        printf("Test number %d\n", i);
        double *x1i = malloc(sizeof(double));
        double *x1r = malloc(sizeof(double));
        double *y1i = malloc(sizeof(double));
        double *y1r = malloc(sizeof(double));
        double *z1i = malloc(sizeof(double));
        double *z1r = malloc(sizeof(double));
        double *x2i = malloc(sizeof(double));
        double *x2r = malloc(sizeof(double));
        double *y2i = malloc(sizeof(double));
        double *y2r = malloc(sizeof(double));
        double *z2i = malloc(sizeof(double));
        double *z2r = malloc(sizeof(double));
        double a = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double b = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *x1i = a;
        *x1r = b;
        x1->Im = x1i;
        x1->Re = x1r;
        double c = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double d = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *y1i = c;
        *y1r = d;
        y1->Re = y1r;
        y1->Im = y1i;
        double e = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double f = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *z1i = e;
        *z1r = f;
        z1->Re = z1r;
        z1->Im = z1i;
        Set_x(v1, (void *) (x1));
        Set_y(v1, (void *) (y1));
        Set_z(v1, (void *) (z1));
        double a2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double b2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *x2i = a2;
        *x2r = b2;
        x2->Im = x2i;
        x2->Re = x2r;
        double c2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double d2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *y2i = c2;
        *y2r = d2;
        y2->Re = y2r;
        y2->Im = y2i;
        double e2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        double f2 = (double) (rand() % 100) / (100 - 1) + rand() % 100;
        *z2i = e2;
        *z2r = f2;
        z2->Re = z2r;
        z2->Im = z2i;
        Set_x(v2, (void *) (x2));
        Set_y(v2, (void *) (y2));
        Set_z(v2, (void *) (z2));
        printf("Check Sum_vector:\n");
        printf("Adding vectors:\n");
        print_vector(v1);
        printf(" + ");
        print_vector(v2);
        printf("\n");
        double newxr = b + b2;
        double newx = a + a2;
        double newy = c + c2;
        double newyr = d + d2;
        double newz = e + e2;
        double newzr = f + f2;
        printf("Expected result: (x = %lf + i*%lf ,y = %lf+ i*%lf ,z = %lf + i*%lf)\nReal result:", newxr, newx, newyr,
               newy, newzr, newz);
        Vector *res = Sum(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Check subtract_vector:\n");
        printf("Subtracting vectors:\n");
        print_vector(v1);
        printf(" - ");
        print_vector(v2);
        newx = a - a2;
        newxr = b - b2;
        newy = c - c2;
        newyr = d - d2;
        newz = e - e2;
        newzr = f - f2;
        printf("Expected result: (x = %lf + i*%lf ,y = %lf+ i*%lf ,z = %lf + i*%lf)\nReal  result:", newxr, newx, newyr,
               newy, newzr, newz);
        res = Subtract(v1, v2);
        print_vector(res);
        printf("\n");
        printf("Check multiply vectors:\n");
        printf("Scalar multiplying:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        double multr = a * a2 + c * c2 + e * e2;
        double multi = b * b2 + d * d2 + f * f2;
        printf("Expected result: \n");
        void *scalres = Multiply_vectors(v1, v2);
        print_complex(scalres);
        printf("\n");
        printf("Real result:\n");
        print_complex(scalres);
        printf("\n");
        printf("Check vector_product:\n");
        printf("Vector product:\n");
        print_vector(v1);
        printf(" * ");
        print_vector(v2);
        printf("\n");
        double hr = d * f2 - f * d2;
        double hi = c * e2 - e * c2;
        double jr = b * f2 - f * b2;
        double ji = a * e2 - e * a2;
        double kr = b * d2 - d * b2;//
        double ki = a * c2 - c * a2;//
        printf("Expected result: \n");
        Vector_Product(v1, v2);
        printf("\n");
        printf("Real result: \n");
        Vector_Product(v1, v2);
        printf("\n");

    }
}

